version: "3.8"
services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - api

  api:
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker
      dockerfile: development/php-fpm/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
    volumes:
      - ./api:/app

  api-php-cli:
    build:
      context: api/docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./api:/app
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app

  api-postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - /var/playground:/var/lib/postgresql/data
    ports:
      - "5455:5432"

  mailer:
    image: mailhog/mailhog

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - "8085:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq/docker/enabled_plugins:/etc/rabbitmq/enabled_plugins
